server:
    port: 8080
spring:
    application:
      name: Hibernate01Application
    cloud:
      zookeeper:
        connect-string: localhost:2181
        config:
            enabled: false
        discovery:
            enabled: true
            register: true
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: dizel
        url: jdbc:oracle:thin:@//localhost:1521/orcl2
        username: c##dizel
    jpa:
        database-platform: org.hibernate.dialect.Oracle12cDialect
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
        show-sql: true
